name: "CI"
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  elixir-ci:
    name: Elixir Lint & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: "28"
          elixir-version: "1.19"

      - name: Cache Elixir dependencies
        uses: actions/cache@v5
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('mix.exs') }}

      - name: Fetch dependencies
        run: make deps

      - name: Compile
        run: make compile

      - name: Format check
        run: make fmt-check

      - name: Lint
        run: make lint

      - name: Run tests
        run: make test
